
import React from 'react';
import { Job, JobStatus, UserRole, AnalyticsData, User, InventoryItem, Notification } from './types';

export const COLORS = {
  BT_PURPLE: '#550065',
  BT_BLUE: '#002D72',
  BT_PINK: '#E10098',
  BT_WHITE: '#FFFFFF',
};

export const MOCK_USERS: User[] = [
  { id: 'OPS_001', username: 'sarah.ops', role: UserRole.ORIT_OPS, region: 'UK_GLOBAL' },
  { id: 'ENG_101', username: 'dave.engineer', role: UserRole.FIELD_AGENT, region: 'Manchester' },
  { id: 'ENG_102', username: 'emma.engineer', role: UserRole.FIELD_AGENT, region: 'London' },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'VOL013-743987',
    customerName: 'Full Fibre 100',
    address: 'Broadband Installation Site',
    postcode: 'M2 5DB',
    serviceType: 'FTTP',
    sla: 'Standard',
    status: JobStatus.ORDER_RECEIVED,
    scheduledDate: '2024-10-26',
    region: 'Manchester',
    coordinates: [53.4808, -2.2426],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10234',
    customerName: 'TechCorp Solutions',
    address: '15 High Street, Manchester',
    postcode: 'M1 1BE',
    serviceType: 'FTTP',
    sla: 'Premium',
    status: JobStatus.ORDER_RECEIVED,
    scheduledDate: '2024-10-25',
    region: 'Manchester',
    coordinates: [53.4839, -2.2446],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10235',
    customerName: 'Greenwich Leisure',
    address: '22 Riverbank Walk, London',
    postcode: 'SE10 9NB',
    serviceType: 'FTTP',
    sla: 'Standard',
    status: JobStatus.ENGINEER_ASSIGNED,
    assignedAgentId: 'ENG_102',
    scheduledDate: '2024-10-24',
    region: 'London',
    coordinates: [51.4826, -0.0077],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-ETH-2024-10236',
    customerName: 'Global Logistics PLC',
    address: 'Logistics Hub, Birmingham',
    postcode: 'B1 1BB',
    serviceType: 'Ethernet',
    sla: 'Premium',
    status: JobStatus.WAITING_FOR_PROCUREMENT,
    scheduledDate: '2024-10-26',
    region: 'Birmingham',
    coordinates: [52.4862, -1.8904],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTC-2024-10237',
    customerName: 'Retail Giant Ltd',
    address: 'Oxford Street, London',
    postcode: 'W1D 1BS',
    serviceType: 'FTTC',
    sla: 'Standard',
    status: JobStatus.JOB_COMPLETED,
    assignedAgentId: 'ENG_102',
    scheduledDate: '2024-10-20',
    region: 'London',
    coordinates: [51.5145, -0.1448],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10238',
    customerName: 'Northern Media Group',
    address: 'MediaCityUK, Salford',
    postcode: 'M50 2EQ',
    serviceType: 'FTTP',
    sla: 'Premium',
    status: JobStatus.ORDER_RECEIVED,
    scheduledDate: '2024-10-27',
    region: 'Manchester',
    coordinates: [53.4719, -2.2985],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-ETH-2024-10239',
    customerName: 'Cambridge Research Inst.',
    address: 'Science Park, Cambridge',
    postcode: 'CB4 0GZ',
    serviceType: 'Ethernet',
    sla: 'Premium',
    status: JobStatus.JOB_IN_PROGRESS,
    assignedAgentId: 'ENG_101',
    scheduledDate: '2024-10-24',
    region: 'Manchester',
    coordinates: [52.2355, 0.1342],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10240',
    customerName: 'Oxford Univ Press',
    address: 'Walton St, Oxford',
    postcode: 'OX2 6DP',
    serviceType: 'FTTP',
    sla: 'Premium',
    status: JobStatus.ENGINEER_ASSIGNED,
    assignedAgentId: 'ENG_102',
    scheduledDate: '2024-10-28',
    region: 'London',
    coordinates: [51.7594, -1.2687],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10241',
    customerName: 'Manchester Arndale',
    address: 'Market St, Manchester',
    postcode: 'M4 3AJ',
    serviceType: 'FTTP',
    sla: 'Standard',
    status: JobStatus.ENGINEER_ASSIGNED,
    assignedAgentId: 'ENG_101',
    scheduledDate: '2024-10-25',
    region: 'Manchester',
    coordinates: [53.4830, -2.2420],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10242',
    customerName: 'Spinningfields Office',
    address: 'Deansgate, Manchester',
    postcode: 'M3 3EB',
    serviceType: 'FTTP',
    sla: 'Premium',
    status: JobStatus.JOB_COMPLETED,
    assignedAgentId: 'ENG_101',
    scheduledDate: '2024-10-22',
    region: 'Manchester',
    coordinates: [53.4794, -2.2506],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-ETH-2024-10243',
    customerName: 'Trafford Park Logistics',
    address: 'Trafford Park, Manchester',
    postcode: 'M17 1WA',
    serviceType: 'Ethernet',
    sla: 'Premium',
    status: JobStatus.JOB_IN_PROGRESS,
    assignedAgentId: 'ENG_101',
    scheduledDate: '2024-10-24',
    region: 'Manchester',
    coordinates: [53.4675, -2.3089],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10244',
    customerName: 'Canary Wharf Finance',
    address: 'Canada Square, London',
    postcode: 'E14 5AB',
    serviceType: 'FTTP',
    sla: 'Premium',
    status: JobStatus.JOB_COMPLETED,
    assignedAgentId: 'ENG_102',
    scheduledDate: '2024-10-21',
    region: 'London',
    coordinates: [51.5054, -0.0235],
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'OR-FTTP-2024-10245',
    customerName: 'Shoreditch Tech Hub',
    address: 'Old Street, London',
    postcode: 'EC1V 9NR',
    serviceType: 'FTTP',
    sla: 'Standard',
    status: JobStatus.JOB_IN_PROGRESS,
    assignedAgentId: 'ENG_102',
    scheduledDate: '2024-10-24',
    region: 'London',
    coordinates: [51.5254, -0.0863],
    lastUpdated: new Date().toISOString(),
  }
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'NT-004',
    title: 'New Order Received',
    message: 'New Full Fibre 100 broadband order received.',
    jobId: 'VOL013-743987',
    timestamp: new Date().toISOString(),
    isRead: false
  },
  {
    id: 'NT-001',
    title: 'New High Priority Order',
    message: 'New FTTP Premium order received for TechCorp Solutions.',
    jobId: 'OR-FTTP-2024-10234',
    timestamp: new Date().toISOString(),
    isRead: false
  },
  {
    id: 'NT-002',
    title: 'Site Check Action Required',
    message: 'Northern Media Group order is awaiting node capacity audit.',
    jobId: 'OR-FTTP-2024-10238',
    timestamp: new Date().toISOString(),
    isRead: false
  },
  {
    id: 'NT-003',
    title: 'System Alert: SLA Risk',
    message: 'Global Logistics PLC order is reaching SLA threshold.',
    jobId: 'OR-ETH-2024-10236',
    timestamp: new Date().toISOString(),
    isRead: false
  }
];

export const MOCK_INVENTORY: InventoryItem[] = [
  { id: 'INV-001', name: 'Nokia G-010G-Q ONT', category: 'Hardware', stock: 145, exchange: 'Central Manchester', status: 'In Stock' },
  { id: 'INV-002', name: '4-Way Passive Splitter', category: 'Hardware', stock: 12, exchange: 'Central Manchester', status: 'Low' },
  { id: 'INV-003', name: 'Connectorised Fibre Cable (30m)', category: 'Cable', stock: 0, exchange: 'Central Manchester', status: 'Out of Stock' },
  { id: 'INV-004', name: 'Nokia G-010G-Q ONT', category: 'Hardware', stock: 89, exchange: 'London East', status: 'In Stock' },
  { id: 'INV-005', name: '32-Way Fibre Splitter', category: 'Hardware', stock: 4, exchange: 'London East', status: 'Low' },
  { id: 'INV-006', name: 'Duct Grade Fibre (100m)', category: 'Cable', stock: 450, exchange: 'London East', status: 'In Stock' },
  { id: 'INV-007', name: 'Ethernet Access Switch v3', category: 'Hardware', stock: 2, exchange: 'Birmingham Hub', status: 'Low' },
];

export const ORIT_ANALYTICS: AnalyticsData = {
  siteCheckSuccessRate: 93.5,
  avgInstallDurationHours: 4.2,
  procurementDelayImpact: 8.4,
  reworkRate: 3.1,
  slaBreachRisk: 5.8,
  regionCompletion: [
    { region: 'London', rate: 94 },
    { region: 'Manchester', rate: 91 },
    { region: 'Birmingham', rate: 89 },
    { region: 'Scotland', rate: 92 },
    { region: 'Wales', rate: 87 }
  ]
};
